version: "3.9"

services:
  web:
    image: django-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - app/.env
    environment:
      DJANGO_SETTINGS_MODULE: "app.settings"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379

  postgres:
    image: postgres:latest
    env_file:
      - app/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - app/.env
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis:latest
    env_file:
      - app/.env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6379

volumes:
  postgres_data:
  redis_data:
