name: Build

on:
  push:
    branches:
      - main

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker-compose -f docker-compose.yml up -d

      - name: Build and Push Docker images
        run: |
          services=("app" "postgres" "pgadmin" "redis") 

          for service in "${services[@]}"; do
            docker-compose -f docker-compose.yml build $service
            docker-compose -f docker-compose.yml push $service
          done
